spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/skillstorm-project-1
        username: tylercausey
        password: alpaca                                  

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8282     

logging:
    level:
        com:
            skillstorm: debug
